#!/bin/bash

set -e

if [ "$#" -ne 0 ]; then
    echo "Usage: oxen-multi-sn-upgrade"
    exit 1
fi

if [ "$UID" -ne 0 ]; then
    echo "This script must be run as root (e.g. via sudo)."
    exit 1
fi

oxend_upgrade=()
ss_upgrade=()
lokinet_upgrade=()

shopt -s nullglob

echo "Finding oxend configs that need upgrade:"
for x in /etc/loki/node-[0-9][0-9].conf; do
    ox="${x/loki/oxen}"
    if [ -e "$ox" ]; then
        echo "Error: $ox already exists, aborting migration to avoid potentially overwriting things" >&2
        exit 1
    fi
    oxend_upgrade+=("$x")
    echo "    - $x"
done

echo "Finding storage server configs that need upgrading:"
for x in /etc/loki/storage-[0-9][0-9].conf; do
    if ! grep -q lmq-port $x; then
        ss_upgrade+=("$x")
        echo "    - $x"
    fi
done

echo "Finding lokinet configs that need upgrading:"
for x in /etc/loki/lokinet-router-[0-9][0-9].ini; do
    if grep -q ^jsonrpc $x; then
        lokinet_upgrade+=("$x")
        echo "    - $x"
    fi
done

if [ "${#oxend_upgrade[@]}${#ss_upgrade[@]}${#lokinet_upgrade[@]}" == "000" ]; then
    echo "Nothing to upgrade"
    exit 0
fi

restarts=()

if [ "${#oxend_upgrade[@]}" -gt 0 ]; then
    read -p "Press enter to rename the above /etc/loki/node-*.conf files to /etc/oxen/node-*.conf, Ctrl-C to abort."
    echo

    for ox in "${oxend_upgrade[@]}"; do
        mv -v "${ox}" "${ox/loki/oxen}"
    done

    restarts+=("oxen-nodes.target")
fi

if [ "${#ss_upgrade[@]}" -gt 0 ]; then
    read -p "Press enter to add the new lmq-port option (on port 202XX) to the above SS configs, Ctrl-C to abort."
    echo

    for ss in "${ss_upgrade[@]}"; do
        num=${ss/*-/}
        num=${num/.conf/}
        echo "lmq-port=202$num" >>$ss
        echo "Added port 202$num to $ss"
    done

    restarts+=("loki-storage-servers.target")
fi

if [ "${#lokinet_upgrade[@]}" -gt 0 ]; then
    read -p "Press enter to change the old jsonrpc= option to rpc=... in the above lokinet configs, Ctrl-C to abort."

    for ln in "${lokinet_upgrade[@]}"; do
        num=${ln/*-/}
        num=${num/.ini/}
        perl -pi -e "s{^jsonrpc=.*}{rpc=ipc:///var/lib/oxen/node-$num/oxend.sock}" $ln
        echo "Updated RPC setting in $ln"
    done

    restarts+=("lokinet-routers.target")
fi

echo -e "\nAll done.  You probably want to run this now:\n\nsystemctl restart ${restarts[*]}\n"
